model:
  activation: relu
  context_backward: 45
  context_forward: 25
  dropout: 0.3
  dropout_attention: 0.8
  dropout_embedding: 0.4
  dropout_rates: 0.6
  hidden_size: 64
  initrange: 0.01
  loss_ratio: 0.25
  mask_ratio: 0.75
  max_spike_count: 20
  n_heads: 1
  n_layers: 5
  norm: layer
  random_ratio: 1.0
  undivided_attn: false
  xavier: false
setup:
  config_dir: configs/
  data_dir: data/
  dataset: mc_rtt
  gpu_idx: -1
  log_eps: 1.0e-07
  runs_dir: runs/
  save_min_bps: -1000.0
  save_model: true
  seed: 100
  subset_seed: 404
train:
  batch_size: 1024
  chop_size: 60
  early_stopping: true
  epochs: 20000
  es_chk_pnt: 0.5
  es_min_bps: 0.1
  init_lr: 0.0005
  mask_max_span: 2
  max_grad_norm: 200.0
  optimizer: AdamW
  ramp_end: 9000
  ramp_start: 4000
  scheduler: Cosine
  sweep_enabled: false
  sweep_epochs: 9999
  sweep_type: random
  val_interval: 10
  val_ratio: 0.05
  val_type: original
  warmup_steps: 4000
  weight_decay: 1.0e-07